version: '3.1'

services:



  db:
    image: mysql:5.6
    restart: always
    ports:
       - 3306:3306
    volumes:
       - /home/mypc/Documents/Projects/Redis/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: common
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --requirepass root
    ports:
      - 6379:6379
    volumes:
        - /home/mypc/Documents/Projects/Redis/redis-data:/data
    networks:
           - common


  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080



networks:
  common:
    ipam:
      driver: default
